name: The build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: the gradle
        uses: gradle/actions/setup-gradle@v3.4.2

      - name: Build
        run: ./gradlew clean build --info --stacktrace

      - name: waiter! waiter! more JARS please!
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs
